# Generated by Django 3.2.12 on 2022-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='AUCTION_DURATION',
            field=models.IntegerField(null=True),
        ),
    ]
